"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ws^t2pi(@a_a%@&qx)g2jf+k!e8x&952*!aw6&gaxw*jel_yek"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '1d0c3a407acd.ngrok-free.app',  # Optional if not using ngrok anymore
    'ecommerce-7vtp64g3y-khalils-projects-462d2e00.vercel.app',
    '.vercel.app',  # Allow subdomains too (wildcard)
]




# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core.apps.CoreConfig",
    "accounts.apps.AccountsConfig",
    "products.apps.ProductsConfig",
    "widget_tweaks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

]

ROOT_URLCONF = "django_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                # so you can use `request` in templates
                "django.template.context_processors.request",
                # CSRF token injection
                "django.template.context_processors.csrf",
                # your auth/login status
                "django.contrib.auth.context_processors.auth",
                # messages framework
                "django.contrib.messages.context_processors.messages",
                # your custom navbar
                "products.context_processors.navbar_categories",
            ],
        },
    },
]


WSGI_APPLICATION = "django_project.wsgi.application"



DATABASES = {
    'default': dj_database_url.config(
        # Fallback for local development:
        default='postgresql://django_user:django_password@localhost:3307/django_db',
        conn_max_age=600,
        ssl_require=True      # enforce SSL in production
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
#added
STATIC_ROOT = BASE_DIR / "staticfiles"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'abdellahelkhalil.kessoum@ensia.edu.dz'
EMAIL_HOST_PASSWORD = 'ugwg edny eisg yhwk'  # Use an app password, not your main password!
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# send emails to admins
ADMINS = [
    ('Site Admin', 'kessoum1205@gmail.com'),
]

# CSRF_TRUSTED_ORIGINS = [
#     "https://1d0c3a407acd.ngrok-free.app",  # <-- use your current ngrok domain, with https!
# ]